# Generated by Django 4.1 on 2022-09-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0002_productdetail_productdetailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoryID',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodies.order')),
                ('productID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goodies.product')),
            ],
        ),
    ]
