# Generated by Django 4.1 on 2022-09-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0005_remove_customer_password_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='discriptionTitle',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
