# Generated by Django 4.1 on 2022-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0006_productdetail_discriptiontitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=370, upload_to='', width_field=350),
        ),
    ]
