# Generated by Django 4.1 on 2022-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
