# Generated by Django 4.1 on 2022-09-03 23:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[370, 350], upload_to=''),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='discriptionTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
