# Generated by Django 4.1 on 2022-09-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0010_alter_customer_username_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodies.product'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
