# Generated by Django 4.1 on 2022-09-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0011_product_availability_product_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True), max_length=255),
        ),
    ]
