# Generated by Django 4.1 on 2022-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
